### ISSUE TITLE
Add helper class "align-center" for text-align:center?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#12]
Couldn't find anything in the new armstrong to do this, if we're doing the inline classes this may make sense if there isn't one already. If this is too much then I'll just use named classes and apply text align there.

**Comment by adamiprinciples** [comment]
.t-align-center{
    text-align: center;
}

.t-align-left{
    text-align: left;
}

.t-align-right{
    text-align: right;
}
