### ISSUE TITLE
Removal of brand-primary and brand-secondary from armstrong

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#13]
Might be a stupid idea, but given that brand-primary is going to be different for every project, and brand-secondary might not even be needed I wonder whether it should go the way of primary-font and be removed from armstrong? I have had a situation in one project where brand-primary was confused with colour-positive. Since brand-primary has become red I've just had similar confusion with color-negative.

In our skeleton project we have a /shared/_variables.scss which is where I manage custom variables, I wonder whether project-specific colours should sit in there instead...

**Comment by adamiprinciples** [comment]
Just overide them in your armstrong-variables-overrides scss. Removal would mean they were no longer usable via bg-[COLOR] etc
