### ISSUE TITLE
Margin and Padding properties don't seem to work

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#2]
Not working on Grid, Row, Col, Text and Heading.

**Comment by simon-rocketmaker** [comment]
Should note that since these stopped working I've switched to using the helper classes in 100% of cases which might be better as they everything e.g. spans, divs etc., not just on custom armstrong components. Therefore would not mind if they were removed.

**Comment by adamiprinciples** [comment]
these have been completely removed in favour of classnames (eg "className="p-top-small m-left-xsmall" etc)
