### ISSUE TITLE
Similar to #19: Variation on TextInput - Ability to suffix with %

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#20]
Tried to use rightIcon={Icon.Icomoon.percent} but it looks shit:
<img width="682" alt="screen shot 2016-07-06 at 11 57 58" src="https://cloud.githubusercontent.com/assets/8873127/16615787/ef737220-4370-11e6-9014-a3bef0939ec8.png">

Similar to: https://github.com/Rocketmakers/armstrong-react/issues/19

**Comment by adamiprinciples** [comment]
just use rightOverlayText
