### ISSUE TITLE
Date picker input requires YYYY/MM/DD in order to display correctly

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#21]
y no DD/MM/YY?
<DatePickerInput icon={Icon.Icomoon.calendar} date="31/03/02" />
NOT
<DatePickerInput icon={Icon.Icomoon.calendar} date="2002/03/31" />

**Comment by jonnystoten** [comment]
In code this is A-OK (it's [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)). The user should preferably be able to type a date that's valid in the browser's locale, so 31/03/89 in UK, 03/31/89 in US. Going to investigate how to do this.

**Comment by jonnystoten** [comment]
Also should parse in strict mode so we error when getting a non-ISO 8601 date from code

**Comment by jonnystoten** [comment]
I'm going to close this and make a new issue for general DatePicker locale stuff.
