### ISSUE TITLE
Add these responsive breakpoints in Armstrong?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#34]
The responsive.scss helper will not be right for everyone, and any alternative is likely going to come up with same issues. We've also talked about adding responsiveness to Armstrong but it'll have to be bulletproof from the start to avoid making breaking changes with the relatively stable Armstrong Grid component. 

Rather than attempt the impossible what about including some sensible responsive variables in Armstrong. By default Armstrong core wouldn't make any use of those breakpoints but **any** responsive solution (be that the responsive addon, or another option) **must** then make use of it. That way we can 

$responsive-xsmall: 380px !default;
$responsive-small: 560px !default;
$responsive-medium: 768px !default;
$responsive-large: 960px !default;

**Comment by adamiprinciples** [comment]
implemented these (from TL):

```
$responsive-large: 70rem !default;
$responsive-medium: 55rem !default;
$responsive-small: 45rem !default;
$responsive-xsmall: 35rem !default;
```
