### ISSUE TITLE
Discussion: Should we remove <SingleColumnRow /> or implement it in a different way?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#36]
FWIW it should be trivial to update in older projects if we choose the route of backwards compatibility.

**Comment by adamiprinciples** [comment]
I've use this a hell-of-a lot, so would be interested to see what the reasoning is behind removing it, as its a pretty monolithic breaking change ;)

**Comment by philmower** [comment]
Could we not just have `<grid><row><content/></row></grid>` and create the "single column row" dynamically? OR create a generic `<container/>` element which gives you the same flexbox based layout as a grid column, but without being tied to a grid structure?

**Comment by simon-rocketmaker** [comment]
I don't think I care enough to get involved in this one. I will probably always do `<Grid><Row><Col></Col></Row></Grid>` as I have a snippet set up for it (I type "gri" and press tab and it pumps out a full grid). I'm rarely in a situation where I'm _sure_ it'll be a one col row as I'm usually playing around with layout so don't want to tie myself in.

@philmower suggestion of `<container />` is interesting though. Might be a different discussion, not sure. Sounds similar to where #29 is going (see recent Slack for more info on this)

**Comment by adamiprinciples** [comment]
I'm not convinced it needs to go... Its a timesaver, and reduces the amount of markup you have to read/write. You don't have to use it and its only 5 lines of code in grid.tsx

`<SingleColumnRow>Hello world</SingleColumnRow>`

vs

```
<Row>
   <Col>Hello world</Col>
</Row>
```

**Comment by adamiprinciples** [comment]
I can't be bothered to maintain this. IT IS GONE (in 1.0)
