### ISSUE TITLE
Future of "centerContent" property

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#37]
Seems to make more semantic sense. I don't mind updating old projects to maintain backwards compatibility.

**Comment by philrocketmaker** [comment]
My concern is that to a newcomer, "centerContent" reads as a boolean property. Only when you read the docs, do you discover that it can take strings, objects and all kinds of other cool stuff. Would it be more intuitive to do something like `horizontalAlignment="left"` and `verticalAlignment="center"`

**Comment by simon-rocketmaker** [comment]
Agree with this. Not hard to make the change if you want to keep your projects up to date, either.

**Comment by adamiprinciples** [comment]
I kinda agree with this, but because its one mighty prop at the moment you can do centerContent="both". Which as you can probably now see, is where it began, and the reason for its name. I guess if its not a normal thing to do horizontalAlignment="center" and verticalAlignment ="center", then the both prop doesnt save time/code. Again, this change will be breaking so need to make sure we all agree

**Comment by simon-rocketmaker** [comment]
I use this a hell of a lot so although this is just splitting hairs maybe we could have something quicker to type e.g. hAlign/horzAlign? Not sure if this is a good idea, but is there something to be said for being able to do something like `<Col align={{top, left}} />`?

**Comment by philmower** [comment]
In your example, how would I specify just left alignment? Or do I have to specify both? I think splitting them out gives greater flexibility and is more intuitive for new users.

We _could_ shorten the property names, but I'd argue that most decent editors will autocomplete it for you anyway?

![screen shot 2016-08-01 at 12 58 02](https://cloud.githubusercontent.com/assets/9843780/17293449/40495b8e-57e8-11e6-9bb1-8cb25cc31ece.png)

**Comment by simon-rocketmaker** [comment]
All good points. Happy with where this feature is going. Like @adamiprinciples idea of putting these into a breaking change release as it'll be easier for me to keep older projects up to date.

**Comment by adamiprinciples** [comment]
done on release 1.0
