### ISSUE TITLE
Future of 'fixed' prop on Grid's Row and Col elements

### ISSUE THREAD

**Issue by philmower** [Rocketmakers/armstrong-react#38]
I have concerns that this prop name gives the impression that it only supports boolean values, when it actually supports both number and boolean. To be more consistent with HTML I suggest we change `<row>` to have a `height` and `<col>` to have `width` property which take either a number or `"auto"` as a string.

**Comment by philmower** [comment]
We could also potentially replace the `spans` prop with `width="*"` or `width="2*"` similar to WPF

**Comment by simon-rocketmaker** [comment]
WHAT THE FUCK, MAN

**Comment by simon-rocketmaker** [comment]
This sounds good to me. I am going to defer to you and Adam on this one as it's probably over my head. Just for a sense check there's no possibility of wanting to use spans="X" and what is currently fixed, is there?

**Comment by philmower** [comment]
My understanding is that `spans` and `fixed` are mutually exclusive. You can't have something that is both fixed in size but also grows to fill available space

**Comment by simon-rocketmaker** [comment]
Seems to make sense to me!

**Comment by adamiprinciples** [comment]
I'm not 100% sure spans even needs to exist any more. This was a property from the old days which kinda hung around. I agree with the width and height props. They make more sense for sure. Again, its a breaking change but one I think we should do. Probably going to bundle all these into one big old 'breaks everything' release

**Comment by simon-rocketmaker** [comment]
I didn't use spans until I saw it in the properties when I was documenting Col. Once I knew it existed it came in handy for something last week, can't remember what, so might suggest we keep the functionality however it ends up looking/working

**Comment by adamiprinciples** [comment]
Fixed in 1.0 :)

**Comment by adamiprinciples** [comment]
Going to re-implement this in a new better way

**Comment by adamiprinciples** [comment]
this is in 1.0. You can now use width="2*" and height="2*" to do star widths
