### ISSUE TITLE
Future of maxCols property.

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#39]
Should this be part of the one/many responsive solutions we have might have to Armstrong, rather than built-in?

**Comment by adamiprinciples** [comment]
With the inclusion of the responsive stuff, maxcols doesn't really bring anything to the table so I'll probably remove it unless anyone objects?

**Comment by simon-rocketmaker** [comment]
I don't use maxCols so don't mind it going. Does prompt a question about responsiveness in Armstrong but I'll create another issue for it.

**Comment by adamiprinciples** [comment]
Feature removed
