### ISSUE TITLE
Future of grid table property/what happened to the React table?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#40]
We currently have a property on the Grid called "table" which applies some css styling. @adamiprinciples what was the thinking behind this?

@WebWalks  I remember hearing you made a table component a while ago (think it may have been used in Abide?!) and wonder whether removing this property from React and making an all-singing, all-dancing table control of our wildest dreams may be an option?

**Comment by adamiprinciples** [comment]
I agree it'd be nice to have a proper data table, but its a decent chunk of work.

As for grids 'table mode', we could remove it if its upsetting people but its a breaking change

**Comment by adamiprinciples** [comment]
It is decided. Imma bin this
