### ISSUE TITLE
Simpler default button styling?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#41]
The TravelLocal buttons look cool but if you want to change them you have to override a few things in every project. Now Armstrong has come on a few versions I think we might benefit from a more vanilla button. Will mean big changes to TravelLocal but am happy to deal with the fallout for TravelLocal myself.

I think removing out the box-shadow (@include button-shadow();) would help
margin-bottom: $spacing-small;

Another thing I tend to override in every project is .btn {margin-bottom: $spacing-small;}. I guess this is in there to cater for the box-shadow, but if that's removed it might not be needed either.

**Comment by adamiprinciples** [comment]
I'm happy to do this, but it'd visually break sites (eg, all travel locals buttons would become flat) so definately a breaking change

**Comment by adamiprinciples** [comment]
Shadows have gone!
