### ISSUE TITLE
Spacing variables and the difference between em's and rem's

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#43]
I've used our spacing variables (which are in rem's) as defaults on a lot of stuff e.g. the padding inside buttons but as @philmower pointed out there is a strong case for some of those being em's so they can be relative to the text size of the element e.g. when text in a button is big, the spacing reflects the font-size (with em's) rather than being a constant size (as it does currently with rem's).

I don't disagree this would be better but there the question is how to do it? All of our spacing variables are in rem's at the moment. Here are some ideas:

1. We have variables for both em's and rem's [unconvinced]
2. We leave as it is and let users add their own variables/override armstrong variables on a per-project basis.
3. We find some way to share a single set of spacing sizes with variables, but allow the flexibility of choosing the unit [seems overkill]
4. We don't do spacing variables at all. [not in favour of this]
5. We "hardcode" em spacing into relevant components where necessary.

My gut feeling says of those options 2 or 5 is best. Worth saying I haven't come across a use case where this has been a real issue in the apps I've been working on (although it's probably more likely to come up in marketing sites) so am on the fence about whether to back this change before they actually become a problem.

**Comment by adamiprinciples** [comment]
We now have a seperate em variable for input/button etc spacing:
```
//// BUTTON & INPUT SPACINGS
$field-padding-vertical: 0.75em;
$field-padding-horizontal: 1em;
```

It's also worth noting, when overriding armstrong variable values, you can also change the unit to whatever you want so I think it's safe to say this one is solved
