### ISSUE TITLE
Consider what is core for armstrong. Move dialog and burger out of Armstrong?

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#44]
In the interest of a) minimising breaking changes to Armstrong and b) staying off the path of "trying to be everything to everyone" maybe we should consider making Dialog and Burger menu an optional add-on and removing them from Armstrong core?

**Comment by adamiprinciples** [comment]
Dialog is very useful. I'm not sure why we'd move it outside.... 
As for burger menu, I'm less bothered. As long as we have a good story for adding it back in later and a good reason for removing it

**Comment by adamiprinciples** [comment]
burger menu is now seperate in a navigation.scss file. Dialog remains
