### ISSUE TITLE
Breaking changes in Armstrong and maintaining support for older projects

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#49]
Seems to be a recurring theme so thought it worth a separate issue. Put your thoughts in this issue:

**Comment by philmower** [comment]
Armstrong 2.0.0!

**Comment by simon-rocketmaker** [comment]
I'm very keen to keep as many projects as possible up to date with Armstrong in it's pre-release (1.0) stage. Worth saying that this may include some extra discussion over breaking changes but most often I think it'll be me going through old projects and updating them. Key points below:

1. Not all areas of Armstrong are at an equal stage. The Grid (discussions around functionality aside) is fairly stable. Form elements are not at the same stage. Making breaking changes and leaving production projects with unsupported versions of Armstrong will make genuine necessary bug fixes and updates more difficult. Which leads on to my second point:

2. IMO Armstrong-react would not have come anywhere near this far without work on production projects. We have used it on at least 6 projects now* (Abide, Gesture, Practitioner/Coach app, Offline medical records, TravelLocal, EIS Costings) and regular production-quality testing and development is an essential part of getting to a best v1.0. Would not be a good situation if we marked them all as abandonware for the sake of features that will never get used/tested because there are no opportunities to use them _for real_.

3. Once reasonably mature (1.0) I think the core of Armstrong will actually be fairly stable (it is not now). There is a possible real benefit in being able to maintain a central core scaffolding for a lot of projects where one menial change can benefit many projects. This is certainly not going to be easy but it is possible, I think.

n.b. not all projects are equal. Some are already way past the point of being worth updating namely Gesture and Practitioner Coach app.

Post version 1 I think the situation may be different.

**Comment by jonnystoten** [comment]
Some ideas:

- Keep a 'next' branch open where breaking changes get committed. Then we can make a major release when there's enough useful stuff to make it worth it. This is the approach taken by node.
- Deprecate things before breaking them. E.g. if we want to remove SingleColumnRow, first make it console.log a warning letting the developer know it's going to be removed in the future. This is the approach taken by react.
- Decide how many versions back we want to support. Keep a branch open for each released major version. Bugfixes can go to all of these branches. This might affect what we support when we hand over to customers?

**Comment by jonnystoten** [comment]
Are we any closer to a decision on this? The issues assigned to me are both breaking changes, but I don't want to paint myself into a corner if I do something that isn't compatible with however we decide to handle breaking changes.

**Comment by adamiprinciples** [comment]
Lets make a release 1.0 branch and start crankin out all the breaking changes on that

**Comment by jonnystoten** [comment]
I'll get on this probably tomorrow.
