### ISSUE TITLE
Add a combobox to the list of components

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#5]
As per EIS top nav search box or...
<img width="771" alt="screen shot 2016-05-31 at 09 36 02" src="https://cloud.githubusercontent.com/assets/8873127/15668449/32dc9e3a-2713-11e6-808a-97c8489e8360.png">

**Comment by adamiprinciples** [comment]
This is now available (just import DropdownSelect). ask me for how to use it as its not doc'd yet
