### ISSUE TITLE
Make DatePickerInput's API only deal in strings, not moments.

### ISSUE THREAD

**Issue by jonnystoten** [Rocketmakers/armstrong-react#53]
Currently, the props `date`, `min`, `max`, and `onDateChanged` can be either strings or moments. We should force them to always be strings.

TravelLocal already uses the string option, but this will be a breaking change that could be a bit horrible for other projects. I'm cool with going through other projects and fixing them up!

**Comment by adamiprinciples** [comment]
jonny, plz rename to calendarinput plz

**Comment by adamiprinciples** [comment]
I renamed for you,dw

**Comment by jonnystoten** [comment]
Done on release/1.0
