### ISSUE TITLE
Upgrade to TypeScript 2.0.5

### ISSUE THREAD

**Issue by jonnystoten** [Rocketmakers/armstrong-react#65]

**Comment by adamiprinciples** [comment]
given the complications we've had over the last few days with this I've had to fork this work:
non-@types - https://github.com/Rocketmakers/armstrong-react/tree/release/1.0
@types - https://github.com/Rocketmakers/armstrong-react/tree/release/1.0-types

We've got a few product releases coming up and there simply isn't the time to get them all working correctly with the new types stuff. I'm probably going to hold off for a bit on merging these until it works better (maybe ts 2.0.5?).

We can start using TS2 in all other aspects (strict null checking etc)

**Comment by adamiprinciples** [comment]
Not a problem anymore
