### ISSUE TITLE
Dialog onClose function is being called twice

### ISSUE THREAD

**Issue by n-s-russell** [Rocketmakers/armstrong-react#68]
The onClose function (optionally) passed as a property to the Armstrong Dialog is called twice when the close button in the top-right of the open modal is clicked.

When a function explicitly setting the isOpen boolean to false is used, the Dialog will close as expected; when a function simply toggles the boolean, as it is called twice, the Dialog will close and then instantaneously open again without any other input from the user.

**Comment by adamiprinciples** [comment]
The behaviour is now as follows : 

- OnClose is now a required prop as not setting this will cause inconsistency between UI and React state.
- Clicking the X to close will now fire OnClose if not handled specifically by the user using OnXClicked.
- OnXClicked should only be used for handling a second 'confirmation' layer dialog.

If you need to programatically close the dialog outside of these cases always set your state boolean (the one you used for isOpen) all other methods to close the dialog are now internal
