### ISSUE TITLE
Multi-select dropdown i.e. tag selector

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#7]
E.g. 
<img width="390" alt="screen shot 2016-06-08 at 11 27 56" src="https://cloud.githubusercontent.com/assets/8873127/15891362/176e211e-2d6c-11e6-8afa-a63a5d82440c.png">

**Comment by adamiprinciples** [comment]
this is in! Simply use multiSelect={true}
