### ISSUE TITLE
flex-basis: auto is breaking some even-column layouts.

### ISSUE THREAD

**Issue by jlews** [Rocketmakers/armstrong-react#73]
`flex-basis` has now been explicitly set to `auto` on `.col` to fix an issue in IE11. This is breaking some even column layouts as it forces flex to look at the specified/computed width of each column individually, whereas it's previous value (`0`), allowed flex to spread the columns evenly if no specific box model widths were declared on the individual columns, regardless of their content (or lack of).

This is causing some columns to collapse, especially if they have no "content" to give them box-model width (columns that contain bg image elements only for example)

**Comment by adamiprinciples** [comment]
This was fixed a couple of versions ago :)
