### ISSUE TITLE
Suggestion: Change default font

### ISSUE THREAD

**Issue by simon-rocketmaker** [Rocketmakers/armstrong-react#9]
In the armstrong prototypes I've been using the following as my $primary-font

$primary-font: -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica, helvetica neue, Ubuntu, segoe ui, arial, sans-serif;

Whilst it looks like a piece of sh*t, it basically pulls the default system font for the OS the user is using, which I think is a nice starting point for a boilerplate and framework. Also having to change it from Averta every time is not idea. For more info including an expanded list of system fonts using this method see: https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/

**Comment by adamiprinciples** [comment]
The issue I have with this is that it's not the same cross browser/platform. If it's going to look poor, we may as well make it look the same across everything. Otherwise if the default font isn't changed for any reason, you'll get different experiences in different browsers/platforms.

**Comment by simon-rocketmaker** [comment]
Not fussed, anything but Averta and Caveat!
